services:
  backend:
    container_name: backend
    build: ./temporary-backend
    ports:
      - "8080:8080"
    environment:
      BACKEND_DB_HOST: mysql
      BACKEND_DB_USER: root
      BACKEND_DB_PASSWORD: password
      BACKEND_DB_NAME: mydatabase
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
